config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  #「/」はhomesコントローラーのTopページを表示
  root to: 'homes#top'

  #URLが「home/about」のとき、homesコントローラーのaboutアクションを探しに行く
  get'home/about' => 'homes#about', as: 'about'

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'default-image.jpg'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/_new.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :Opinion %>
    <%= f.text_field :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign_up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-5">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Bookers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house-chimney"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-users"></i>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-book-open"></i>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-from-bracket"></i>Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house-chimney"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-link"></i>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-to-bracket"></i>Log in
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7f05cc38f0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<table class="table">
  <tr><%= image_tag user.get_profile_image, size: "100x100" %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<div class="row mb-2">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "user_info", user: @user %>
      <h2>New book</h2>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/index" %>
    </div>
  </div>
</div>